101-manage_my_process, manage_my_process

diff --git a/0x05-processes_and_signals/101-manage_my_process b/0x05-processes_and_signals/101-manage_my_process
--- a/0x05-processes_and_signals/101-manage_my_process
+++ b/0x05-processes_and_signals/101-manage_my_process
@@ -1,28 +1,60 @@
 #!/bin/bash
 
+# Define paths
+PID_FILE="/var/run/my_process.pid"
+SCRIPT="./manage_my_process"
+
+# Check if argument is provided
+if [ $# -eq 0 ]; then
+    echo "Usage: $0 {start|stop|restart}"
+    exit 1
+fi
+
+# Function to start the process
+start_process() {
+    if [ -f "$PID_FILE" ]; then
+        echo "Error: $SCRIPT is already running."
+        exit 1
+    else
+        $SCRIPT &
+        echo $! > $PID_FILE
+        echo "$SCRIPT started"
+    fi
+}
+
+# Function to stop the process
+stop_process() {
+    if [ -f "$PID_FILE" ]; then
+        PID=$(cat $PID_FILE)
+        sudo kill $PID
+        rm $PID_FILE
+        echo "$SCRIPT stopped"
+    else
+        echo "Error: $SCRIPT is not running."
+        exit 1
+    fi
+}
+
+# Function to restart the process
+restart_process() {
+    stop_process
+    start_process
+    echo "$SCRIPT restarted"
+}
+
+# Main script logic
 case "$1" in
     start)
-        ./manage_my_process &
-        echo $! > /var/run/my_process.pid
-        echo "manage_my_process started"
+        start_process
         ;;
     stop)
-        if [ -e /var/run/my_process.pid ]; then
-            PID=$(cat /var/run/my_process.pid)
-            kill $PID
-            rm /var/run/my_process.pid
-            echo "manage_my_process stopped"
-        else
-            echo "manage_my_process is not running"
-        fi
+        stop_process
         ;;
     restart)
-        $0 stop
-        sleep 2
-        $0 start
-        echo "manage_my_process restarted"
+        restart_process
         ;;
     *)
         echo "Usage: $0 {start|stop|restart}"
         exit 1
 esac
+
